export const manufacturers = [
  "Acura",
  "Alfa Romeo",
  "Aston Martin",
  "Audi",
  "Bentley",
  "BMW",
  "Buick",
  "Cadillac",
  "Chevrolet",
  "Chrysler",
  "Citroen",
  "Dodge",
  "Ferrari",
  "Fiat",
  "Ford",
  "GMC",
  "Honda",
  "Hyundai",
  "Infinity",
  "Jaguar",
  "Jeep",
  "Kia",
  "Lamborghini",
  "Land Rover",
  "Lexus",
  "Lincoln",
  "Maserati",
  "Mazda",
  "McLaren",
  "Mercedes-Benz",
  "MINI",
  "Mitsubishi",
  "Nissan",
  "Porsche",
  "Ram",
  "Rolls-Royce",
  "Subaru",
  "Tesla",
  "Toyota",
  "Volkswagen",
  "Volvo",
];

export const yearsOfProduction = [
  { id: 1, title: "Year", value: "" },
  { id: 2, title: "2015", value: "2015" },
  { id: 3, title: "2016", value: "2016" },
  { id: 4, title: "2017", value: "2017" },
  { id: 5, title: "2018", value: "2018" },
  { id: 6, title: "2019", value: "2019" },
  { id: 7, title: "2020", value: "2020" },
  { id: 8, title: "2021", value: "2021" },
  { id: 9, title: "2022", value: "2022" },
  { id: 10, title: "2023", value: "2023" },
];

export const fuels = [
  {
    id: 1,
    title: "Fuel",
    value: "",
  },
  {
    id: 2,
    title: "Gas",
    value: "Gas",
  },
  {
    id: 3,
    title: "Electricity",
    value: "Electricity",
  },
];

export const footerLinks = [
  {
    id: "A",
    title: "About",
    links: [
      { id: 1, title: "How it works", url: "/" },
      { id: 2, title: "Featured", url: "/" },
      { id: 3, title: "Partnership", url: "/" },
      { id: 4, title: "Business Relation", url: "/" },
    ],
  },
  {
    id: "B",
    title: "Company",
    links: [
      { id: 1, title: "Events", url: "/" },
      { id: 2, title: "Blog", url: "/" },
      { id: 3, title: "Podcast", url: "/" },
      { id: 4, title: "Invite a friend", url: "/" },
    ],
  },
  {
    id: "C",
    title: "Socials",
    links: [
      { id: 1, title: "Discord", url: "/" },
      { id: 2, title: "Instagram", url: "/" },
      { id: 3, title: "Twitter", url: "/" },
      { id: 4, title: "Facebook", url: "/" },
    ],
  },
];
